UEFI Secure Boot Part 1: chain of trust
coiby/coiby.github.io pull request #1
Opened 2022-02-04 06:30 UTC by coiby

2022-04-22 09:29 UTC, kahboom requested changes

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +It's expected that you still feel confused with the concepts. So I will first talk about Public-key cryptography and HTTPS chain of trust to hell you grasp these concepts. From the perspective of pub
I would remove this part "It's expected that you still feel confused with the concepts. So" so we don't assume the user is confused yet. Or maybe, "If you're still confused, don't worry, I'll first go through Public-key cryptography  and HTTPS chain of trust to help you grasp these concepts."

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +It's expected that you still feel confused with the concepts. So I will first talk about Public-key cryptography and HTTPS chain of trust to hell you grasp these concepts. From the perspective of pub
"hell you grasp" -> "help you grasp"

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +Suppose you want to send a message to your friend over the Internet, but what if someone is eavesdropping you? Something occurs to your mind could be to have the message encrypted with a key as we wo
"Something occurs to your mind could be to have the message encrypted with a key as we would use the key to lock the door." -> maybe something like "You get the idea to have the message encrypted with a key, much like using a key to lock a door." ?

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +Suppose you want to send a message to your friend over the Internet, but what if someone is eavesdropping you? Something occurs to your mind could be to have the message encrypted with a key as we wo
"Remember someone is eavesdropping you right now." -> "Remember, you're being eavesdropped on."

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +In the case of safely browsing the Internet, the trust model involves more than one certificate authority. The so called chain of trust includes end-user certificate, intermediate certificate, and ro
"The so-called chain of trust includes an end-user certificate, an intermediate certificate, and a root certificate."

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +In the chain of trust, your root trust is the root authority. Then the trust extends to immediate certificate which in turn to the end-entity certificate finally,
"The trust then extends to the immediate certificate which, in turn, extends to the end-entity certificate."

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +signature^{65537} \bmod modulus
Maybe it would be good to explain a little bit more about what the formula means? Unless it's too complex and might confuse the user or distract them from the point.

2022-04-22 09:29 UTC, kahboom commented on _posts/2022-02-04-uefi_part1.md
> +
Could be good to have a final conclusion here, maybe mention how this applies to websites and how it's a part of our everyday lives?

2022-12-29 01:07 UTC, coiby commented on _posts/2022-02-04-uefi_part1.md
> +signature^{65537} \bmod modulus
Thanks for the suggestion! Unfortunately, to explain the formula will involve more concepts that myself hasn't  understood.

2022-12-29 01:08 UTC, coiby commented on _posts/2022-02-04-uefi_part1.md
> +
Thanks for the suggestion! I've added a final conclusion!

2022-12-29 01:08 UTC, merged